### ISSUE TITLE
Use an alternative to reprepro

### ISSUE THREAD

**Issue by ppp0** [cargomedia/debian-packages#105]
Until `reprepro` does not support the inclusion of several versions of the same package in its database ([there is a patch to allow for this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=570623)), move our package database creation to either

- https://www.aptly.info - probably deserves the distinction *swiss army knife*
- https://github.com/rcrowley/freight (Description in [Debian packaging for busy people](https://rcrowley.org/articles/packaging.html))

**Comment by njam** [comment]
Not needed
