### ISSUE TITLE
Fix paths for all gstreamer debs

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/debian-packages#110]
With `1.8.0` it installs to `/usr/lib/x86_64-linux-gnu/` but was installed to `/usr/local/lib/` with `1.6.1`

Binaries should go to `/usr/local/bin/` but are installed wrongly into `/usr/bin/`

**Comment by kris-lab** [comment]
Closing. This is not a case anymore.

**Comment by njam** [comment]
Where does it install to?

**Comment by kris-lab** [comment]
It installs to `/usr/lib/x86_64-linux-gnu/` which is fine! 

I was confused because we had binaries for `gst-inspect-1.0` and `gst-launch-1.0` also installed  in `/usr/local/bin` (e.g. version 1.6.1) and by default Linux runs `/usr/local/bin` and not `/usr/bin`. It finished up with loading libs from `/usr/local/lib/gstreamer-1.0` instead of `/usr/lib/x86_64-linux-gnu/gstreamer-1.0`.

When I removed all `gst` binaries from `/usrc/local/bin` it runs `/usr/bin` (correct version 1.8.0) binaries which load proper `libs` :)

Hope this is understandable!
