### ISSUE TITLE
[janus-gateway-rtpbroadcast] - Check distro-based dependencies

### ISSUE THREAD

**Issue by ppp0** [cargomedia/debian-packages#128]
When trying to upgrade on Wheezy, the package shows up as kept back:
```
The following packages have unmet dependencies:
 janus-gateway-rtpbroadcast : Depends: libc6 (>= 2.14) but 2.13-38+deb7u11 is to be installed
E: Unable to correct problems, you have held broken packages.
```

* Building on Wheezy did not solve the problem
* No issues on Jessie

**Comment by njam** [comment]
On second thought I think we should anyway build it using the target distro.
Because compilation will use all the libraries of *that* environment.

IMO we can close this, and just make sure to build using the target distro.

**Comment by ppp0** [comment]
Otoh, I built it on Wheezy to check and still it was failing. Let's bump the version and redo the steps by building the packages on a each distro's VM

**Comment by njam** [comment]
Still because of libc?
What was the error? What was the `control` file's contents?

**Comment by ppp0** [comment]
Sorry, I was mistaken. I re-updated (`apt-get update`) and re-tried.. Now, the dependency mismatch is gone (pkg built with a Wheezy VM)! May be some delay due to s3 cache invalidation.. 

The error was the same, btw (wrong libc6 dependency)

**Comment by ppp0** [comment]
On the other hand, by building packages on the *oldest* distro we can check what the *minimum* version for a library is - in this case: `libc >=2.13-38` - @njam thoughts?

**Comment by njam** [comment]
Not sure, but I can imagine that the libraries on the system affect the binaries.
To be safe I would build on the target platform?
