### ISSUE TITLE
will support  xenial ?

### ISSUE THREAD

**Issue by notedit** [cargomedia/debian-packages#147]
i try to use this in xenial.

got this error 

```
E: Failed to fetch http://debian-packages.cargomedia.ch/dists/xenial/main/binary-amd64/Packages  403  Forbidden [IP: 112.124.140.210 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by njam** [comment]
At the moment only Ubuntu vivid (and Debian jessie) is supported. Some packages even only in one codename. We will not provide xenial packages anytime soon.

But pull requests are very welcome!
