### ISSUE TITLE
add libsrtp as dependency for janus rtpbroadcast

### ISSUE THREAD

**Issue by dergraf** [cargomedia/debian-packages#66]

**Comment by dergraf** [comment]
quickly checked the required libsrtp is linked as a static library into janus (included as a janus build dependency). For this reason it isn't required to have it as a install dependency.
@ppp0 any comments?

**Comment by ppp0** [comment]
Agree, but isn't it possible to add it to the `Depends` in `debian/control` ?

e.g.
```
[..]
Package: janus-gateway-rtpbroadcast
Architecture: any
Section: net
Depends: ${misc:Depends},
         ${shlibs:Depends}
         libsrtp (>= version)  <---------------------- This line
Description: Cargomedia propretary Janus RTP broadcast plugin
```

**Comment by dergraf** [comment]
it is, but unnecessary IMO.

**Comment by dergraf** [comment]
BTW. if we would like to include the libsrtp, then it would rather be a dependency of the janus package. Afaict the rtpbroadcast doesn't use the libsrtp directly.

**Comment by ppp0** [comment]
So sorry, you said
>it isn't required to have it as a install dependency.

agree, then, scrap it
